"""ALIGNN 2.0 pretrained-model registry (glossary).

Analogous to :mod:`jarvis.db.figshare`: a single dict maps a model name to its
Figshare artifacts and metadata, and :func:`get_alignn2_model` downloads
(and caches) the ``config.json``, ``best_model.pt``, and
``ids_train_val_test.json`` for that model.

All models live in the Figshare **ALIGNN2** project
(https://figshare.com/projects/ALIGNN2, id ``279395``). Each variant (e.g.
``formation_energy_peratom_radius`` and ``..._knn``) is its OWN article holding
ONE flat zip (best_model.pt + config.json + ids_train_val_test.json) with its
own ``url`` (``https://ndownloader.figshare.com/files/<id>``) -- mirroring the
per-model download URLs in the original ``alignn/pretrained.py``.

Note: Figshare *draft* files are not publicly downloadable; the ``url`` loader
activates once the article is published (token needed meanwhile).
"""

import os
import zipfile
import requests

FIGSHARE_PROJECT_ID = 279395
FIGSHARE_PROJECT_URL = "https://figshare.com/projects/ALIGNN2/{}".format(
    FIGSHARE_PROJECT_ID
)

# --- registry -----------------------------------------------------------------
# name -> metadata. Each entry carries its own `url` (one flat zip per variant).
ALIGNN2_MODELS = {
    "alex_supercon_Tc": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "alex_Tc",
        "unit": "",
        "test_mae": 0.883,
        "figshare_article_id": 33135179,
        "url": "https://ndownloader.figshare.com/files/67163582",
        "description": "Alexandria superconductor Tc (radius).",
    },
    "alex_supercon_debye": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "alex_debye",
        "unit": "",
        "test_mae": 11.33,
        "figshare_article_id": 33135185,
        "url": "https://ndownloader.figshare.com/files/67163588",
        "description": "Alexandria superconductor debye (radius).",
    },
    "alex_supercon_dosef": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "alex_dosef",
        "unit": "",
        "test_mae": 0.821,
        "figshare_article_id": 33135182,
        "url": "https://ndownloader.figshare.com/files/67163585",
        "description": "Alexandria superconductor dosef (radius).",
    },
    "alex_supercon_la": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "alex_la",
        "unit": "",
        "test_mae": 0.0707,
        "figshare_article_id": 33135188,
        "url": "https://ndownloader.figshare.com/files/67163591",
        "description": "Alexandria superconductor la (radius).",
    },
    "alex_supercon_wlog": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "alex_wlog",
        "unit": "",
        "test_mae": 20.31,
        "figshare_article_id": 33135191,
        "url": "https://ndownloader.figshare.com/files/67163597",
        "description": "Alexandria superconductor wlog (radius).",
    },
    "avg_elec_mass_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "avg_elec_mass",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33134975,
        "url": "https://ndownloader.figshare.com/files/67163339",
        "description": "JARVIS-DFT avg_elec_mass (radius graph).",
    },
    "avg_hole_mass_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "avg_hole_mass",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33134981,
        "url": "https://ndownloader.figshare.com/files/67163345",
        "description": "JARVIS-DFT avg_hole_mass (radius graph).",
    },
    "bulk_modulus_kv_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "bulk_modulus_kv",
        "unit": "",
        "test_mae": 9.8854,
        "figshare_article_id": 33134987,
        "url": "https://ndownloader.figshare.com/files/67163351",
        "description": "JARVIS-DFT bulk_modulus_kv (radius graph).",
    },
    "c2db_gap_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "gap",
        "unit": "",
        "test_mae": 0.0971,
        "figshare_article_id": 33135236,
        "url": "https://ndownloader.figshare.com/files/67163642",
        "description": "c2db gap (radius).",
    },
    "dfpt_piezo_max_dielectric_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "dfpt_piezo_max_dielectric",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33134993,
        "url": "https://ndownloader.figshare.com/files/67163357",
        "description": "JARVIS-DFT dfpt_piezo_max_dielectric (radius graph).",
    },
    "dfpt_piezo_max_dij_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "dfpt_piezo_max_dij",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33134999,
        "url": "https://ndownloader.figshare.com/files/67163363",
        "description": "JARVIS-DFT dfpt_piezo_max_dij (radius graph).",
    },
    "ehull_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "ehull",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135005,
        "url": "https://ndownloader.figshare.com/files/67163369",
        "description": "JARVIS-DFT ehull (radius graph).",
    },
    "encut_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "encut",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135011,
        "url": "https://ndownloader.figshare.com/files/67163375",
        "description": "JARVIS-DFT encut (radius graph).",
    },
    "epsx_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "epsx",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135017,
        "url": "https://ndownloader.figshare.com/files/67163381",
        "description": "JARVIS-DFT epsx (radius graph).",
    },
    "epsy_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "epsy",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135023,
        "url": "https://ndownloader.figshare.com/files/67163387",
        "description": "JARVIS-DFT epsy (radius graph).",
    },
    "epsz_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "epsz",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135029,
        "url": "https://ndownloader.figshare.com/files/67163393",
        "description": "JARVIS-DFT epsz (radius graph).",
    },
    "exfoliation_energy_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "exfoliation_energy",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135041,
        "url": "https://ndownloader.figshare.com/files/67163405",
        "description": "JARVIS-DFT exfoliation_energy (radius graph).",
    },
    "formation_energy_peratom_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "formation_energy_peratom",
        "unit": "",
        "test_mae": 0.0316,
        "figshare_article_id": 33135047,
        "url": "https://ndownloader.figshare.com/files/67163411",
        "description": "JARVIS-DFT formation_energy_peratom (radius graph).",
    },
    "halide_peroskites_HSE_decomp_energy_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "HSE_decomp_energy",
        "unit": "",
        "test_mae": 0.0233,
        "figshare_article_id": 33135434,
        "url": "https://ndownloader.figshare.com/files/67164215",
        "description": "halide_peroskites HSE_decomp_energy (radius).",
    },
    "halide_peroskites_HSE_gap_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "HSE_gap",
        "unit": "",
        "test_mae": 0.1397,
        "figshare_article_id": 33135401,
        "url": "https://ndownloader.figshare.com/files/67164101",
        "description": "halide_peroskites HSE_gap (radius).",
    },
    "halide_peroskites_PBE_decomp_energy_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "PBE_decomp_energy",
        "unit": "",
        "test_mae": 0.0265,
        "figshare_article_id": 33135425,
        "url": "https://ndownloader.figshare.com/files/67164152",
        "description": "halide_peroskites PBE_decomp_energy (radius).",
    },
    "halide_peroskites_PBE_gap_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "PBE_gap",
        "unit": "",
        "test_mae": 0.101,
        "figshare_article_id": 33135395,
        "url": "https://ndownloader.figshare.com/files/67164095",
        "description": "halide_peroskites PBE_gap (radius).",
    },
    "halide_peroskites_Ref_ind_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "Ref_ind",
        "unit": "",
        "test_mae": 0.0127,
        "figshare_article_id": 33135416,
        "url": "https://ndownloader.figshare.com/files/67164140",
        "description": "halide_peroskites Ref_ind (radius).",
    },
    "kpoint_length_unit_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "kpoint_length_unit",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135053,
        "url": "https://ndownloader.figshare.com/files/67163420",
        "description": "JARVIS-DFT kpoint_length_unit (radius graph).",
    },
    "magmom_oszicar_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "magmom_oszicar",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135059,
        "url": "https://ndownloader.figshare.com/files/67163426",
        "description": "JARVIS-DFT magmom_oszicar (radius graph).",
    },
    "max_efg_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "max_efg",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135065,
        "url": "https://ndownloader.figshare.com/files/67163450",
        "description": "JARVIS-DFT max_efg (radius graph).",
    },
    "mbj_bandgap_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "mbj_bandgap",
        "unit": "",
        "test_mae": 0.2721,
        "figshare_article_id": 33135071,
        "url": "https://ndownloader.figshare.com/files/67163456",
        "description": "JARVIS-DFT mbj_bandgap (radius graph).",
    },
    "mepsx_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "mepsx",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135077,
        "url": "https://ndownloader.figshare.com/files/67163462",
        "description": "JARVIS-DFT mepsx (radius graph).",
    },
    "mepsy_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "mepsy",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135083,
        "url": "https://ndownloader.figshare.com/files/67163468",
        "description": "JARVIS-DFT mepsy (radius graph).",
    },
    "mepsz_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "mepsz",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135089,
        "url": "https://ndownloader.figshare.com/files/67163474",
        "description": "JARVIS-DFT mepsz (radius graph).",
    },
    "mxene275_formation_energy_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "formation_energy",
        "unit": "eV/atom",
        "test_mae": 0.0348,
        "figshare_article_id": 33135221,
        "url": "https://ndownloader.figshare.com/files/67163627",
        "description": "mxene275 formation energy (radius).",
    },
    "n_Seebeck_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "n_Seebeck",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135095,
        "url": "https://ndownloader.figshare.com/files/67163480",
        "description": "JARVIS-DFT n_Seebeck (radius graph).",
    },
    "n_powerfact_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "n_powerfact",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135101,
        "url": "https://ndownloader.figshare.com/files/67163486",
        "description": "JARVIS-DFT n_powerfact (radius graph).",
    },
    "omdb_bandgap_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "bandgap",
        "unit": "",
        "test_mae": 0.2428,
        "figshare_article_id": 33135329,
        "url": "https://ndownloader.figshare.com/files/67163978",
        "description": "omdb bandgap (radius).",
    },
    "optb88vdw_bandgap_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "optb88vdw_bandgap",
        "unit": "",
        "test_mae": 0.1314,
        "figshare_article_id": 33135107,
        "url": "https://ndownloader.figshare.com/files/67163492",
        "description": "JARVIS-DFT optb88vdw_bandgap (radius graph).",
    },
    "optb88vdw_total_energy_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "optb88vdw_total_energy",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135113,
        "url": "https://ndownloader.figshare.com/files/67163501",
        "description": "JARVIS-DFT optb88vdw_total_energy (radius graph).",
    },
    "pdbbind_binding_affinity_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "binding_affinity",
        "unit": "",
        "test_mae": 1.5833,
        "figshare_article_id": 33135335,
        "url": "https://ndownloader.figshare.com/files/67163984",
        "description": "pdbbind binding_affinity (radius).",
    },
    "polymer_genome_gga_gap_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "gga_gap",
        "unit": "",
        "test_mae": 0.2274,
        "figshare_article_id": 33135230,
        "url": "https://ndownloader.figshare.com/files/67163636",
        "description": "polymer_genome gga_gap (radius).",
    },
    "shear_modulus_gv_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "shear_modulus_gv",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135119,
        "url": "https://ndownloader.figshare.com/files/67163507",
        "description": "JARVIS-DFT shear_modulus_gv (radius graph).",
    },
    "slme_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "slme",
        "unit": "",
        "test_mae": 4.4929,
        "figshare_article_id": 33135125,
        "url": "https://ndownloader.figshare.com/files/67163516",
        "description": "JARVIS-DFT slme (radius graph).",
    },
    "snumat_Band_gap_HSE_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "Band_gap_HSE",
        "unit": "",
        "test_mae": 0.368,
        "figshare_article_id": 33135974,
        "url": "https://ndownloader.figshare.com/files/67166069",
        "description": "snumat Band_gap_HSE (radius).",
    },
    "spillage_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "spillage",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135131,
        "url": "https://ndownloader.figshare.com/files/67163522",
        "description": "JARVIS-DFT spillage (radius graph).",
    },
    "tc_supercon_hydride_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "Tc_supercon_hydride",
        "unit": "K",
        "test_mae": 10.06,
        "figshare_article_id": 33135215,
        "url": "https://ndownloader.figshare.com/files/67163621",
        "description": "Tc_supercon_hydride (radius, retrained pure-torch).",
    },
    "tc_supercon_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "Tc_supercon",
        "unit": "",
        "test_mae": 1.637,
        "figshare_article_id": 33135209,
        "url": "https://ndownloader.figshare.com/files/67163615",
        "description": "Tc_supercon (radius).",
    },
    "thermal_cond_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "ltc",
        "unit": "",
        "test_mae": 0.386,
        "figshare_article_id": 33135194,
        "url": "https://ndownloader.figshare.com/files/67163600",
        "description": "Lattice thermal cond. log10(kL) (radius).",
    },
    "twod_matpd_bandgap_radius": {
        "category": "radius",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "bandgap",
        "unit": "",
        "test_mae": 0.3802,
        "figshare_article_id": 33135242,
        "url": "https://ndownloader.figshare.com/files/67163648",
        "description": "twod_matpd bandgap (radius).",
    },
    "alex_supercon_Tc_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "alex_Tc",
        "unit": "K",
        "test_mae": 0.864,
        "figshare_article_id": 33217413,
        "url": "https://ndownloader.figshare.com/files/67452759",
        "description": "Alexandria superconductor Tc (kNN).",
    },
    "alex_supercon_debye_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "alex_debye",
        "unit": "K",
        "test_mae": 10.68,
        "figshare_article_id": 33217422,
        "url": "https://ndownloader.figshare.com/files/67452771",
        "description": "Alexandria superconductor Debye temperature (kNN).",
    },
    "alex_supercon_dosef_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "alex_dosef",
        "unit": "",
        "test_mae": 0.791,
        "figshare_article_id": 33217419,
        "url": "https://ndownloader.figshare.com/files/67452762",
        "description": "Alexandria superconductor N(E_F) (kNN).",
    },
    "alex_supercon_la_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "alex_la",
        "unit": "",
        "test_mae": 0.0679,
        "figshare_article_id": 33217428,
        "url": "https://ndownloader.figshare.com/files/67452774",
        "description": "Alexandria superconductor lambda (kNN).",
    },
    "alex_supercon_wlog_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "alex_wlog",
        "unit": "K",
        "test_mae": 20.08,
        "figshare_article_id": 33217431,
        "url": "https://ndownloader.figshare.com/files/67452777",
        "description": "Alexandria superconductor omega_log (kNN).",
    },
    "avg_elec_mass_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "avg_elec_mass",
        "unit": "",
        "test_mae": 0.081,
        "figshare_article_id": 33134978,
        "url": "https://ndownloader.figshare.com/files/67163342",
        "description": "JARVIS-DFT avg_elec_mass (knn graph).",
    },
    "avg_hole_mass_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "avg_hole_mass",
        "unit": "",
        "test_mae": 0.124,
        "figshare_article_id": 33134984,
        "url": "https://ndownloader.figshare.com/files/67163348",
        "description": "JARVIS-DFT avg_hole_mass (knn graph).",
    },
    "bulk_modulus_kv_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "bulk_modulus_kv",
        "unit": "",
        "test_mae": 9.302,
        "figshare_article_id": 33134990,
        "url": "https://ndownloader.figshare.com/files/67163354",
        "description": "JARVIS-DFT bulk_modulus_kv (knn graph).",
    },
    "c2db_gap_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "gap",
        "unit": "",
        "test_mae": 0.0802,
        "figshare_article_id": 33135239,
        "url": "https://ndownloader.figshare.com/files/67163645",
        "description": "c2db gap (knn).",
    },
    "dfpt_piezo_max_dielectric_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "dfpt_piezo_max_dielectric",
        "unit": "",
        "test_mae": 24.3052,
        "figshare_article_id": 33134996,
        "url": "https://ndownloader.figshare.com/files/67163360",
        "description": "JARVIS-DFT dfpt_piezo_max_dielectric (knn graph).",
    },
    "dfpt_piezo_max_dij_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "dfpt_piezo_max_dij",
        "unit": "",
        "test_mae": 12.4983,
        "figshare_article_id": 33135002,
        "url": "https://ndownloader.figshare.com/files/67163366",
        "description": "JARVIS-DFT dfpt_piezo_max_dij (knn graph).",
    },
    "ehull_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "ehull",
        "unit": "",
        "test_mae": 0.059,
        "figshare_article_id": 33135008,
        "url": "https://ndownloader.figshare.com/files/67163372",
        "description": "JARVIS-DFT ehull (knn graph).",
    },
    "encut_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "encut",
        "unit": "",
        "test_mae": 128.0826,
        "figshare_article_id": 33135014,
        "url": "https://ndownloader.figshare.com/files/67163378",
        "description": "JARVIS-DFT encut (knn graph).",
    },
    "epsx_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "epsx",
        "unit": "",
        "test_mae": 20.1393,
        "figshare_article_id": 33135020,
        "url": "https://ndownloader.figshare.com/files/67163384",
        "description": "JARVIS-DFT epsx (knn graph).",
    },
    "epsy_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "epsy",
        "unit": "",
        "test_mae": 19.8292,
        "figshare_article_id": 33135026,
        "url": "https://ndownloader.figshare.com/files/67163390",
        "description": "JARVIS-DFT epsy (knn graph).",
    },
    "epsz_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "epsz",
        "unit": "",
        "test_mae": 19.4531,
        "figshare_article_id": 33135032,
        "url": "https://ndownloader.figshare.com/files/67163396",
        "description": "JARVIS-DFT epsz (knn graph).",
    },
    "exfoliation_energy_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "exfoliation_energy",
        "unit": "",
        "test_mae": 37.6285,
        "figshare_article_id": 33135044,
        "url": "https://ndownloader.figshare.com/files/67163408",
        "description": "JARVIS-DFT exfoliation_energy (knn graph).",
    },
    "formation_energy_peratom_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "formation_energy_peratom",
        "unit": "",
        "test_mae": 0.0307,
        "figshare_article_id": 33135050,
        "url": "https://ndownloader.figshare.com/files/67163414",
        "description": "JARVIS-DFT formation_energy_peratom (knn graph).",
    },
    "halide_peroskites_HSE_decomp_energy_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "HSE_decomp_energy",
        "unit": "",
        "test_mae": 0.0233,
        "figshare_article_id": 33135437,
        "url": "https://ndownloader.figshare.com/files/67164218",
        "description": "halide_peroskites HSE_decomp_energy (knn).",
    },
    "halide_peroskites_HSE_gap_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "HSE_gap",
        "unit": "",
        "test_mae": 0.1383,
        "figshare_article_id": 33135404,
        "url": "https://ndownloader.figshare.com/files/67164104",
        "description": "halide_peroskites HSE_gap (knn).",
    },
    "halide_peroskites_PBE_decomp_energy_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "PBE_decomp_energy",
        "unit": "",
        "test_mae": 0.0273,
        "figshare_article_id": 33135428,
        "url": "https://ndownloader.figshare.com/files/67164155",
        "description": "halide_peroskites PBE_decomp_energy (knn).",
    },
    "halide_peroskites_PBE_gap_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "PBE_gap",
        "unit": "",
        "test_mae": 0.0867,
        "figshare_article_id": 33135398,
        "url": "https://ndownloader.figshare.com/files/67164098",
        "description": "halide_peroskites PBE_gap (knn).",
    },
    "halide_peroskites_Ref_ind_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "Ref_ind",
        "unit": "",
        "test_mae": 0.0127,
        "figshare_article_id": 33135419,
        "url": "https://ndownloader.figshare.com/files/67164143",
        "description": "halide_peroskites Ref_ind (knn).",
    },
    "hmof_co2": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "hmof_co2",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135173,
        "url": "https://ndownloader.figshare.com/files/67163576",
        "description": "hMOF CO2 uptake (kNN).",
    },
    "hmof_co2_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "co2_uptake",
        "unit": "mol/kg",
        "test_mae": 0.4687,
        "figshare_article_id": 33137036,
        "url": "https://ndownloader.figshare.com/files/67174418",
        "description": "hMOF CO2 uptake (knn graph, epoch-99).",
    },
    "kpoint_length_unit_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "kpoint_length_unit",
        "unit": "",
        "test_mae": 9.342,
        "figshare_article_id": 33135056,
        "url": "https://ndownloader.figshare.com/files/67163423",
        "description": "JARVIS-DFT kpoint_length_unit (knn graph).",
    },
    "magmom_oszicar_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "magmom_oszicar",
        "unit": "",
        "test_mae": 0.2567,
        "figshare_article_id": 33135062,
        "url": "https://ndownloader.figshare.com/files/67163429",
        "description": "JARVIS-DFT magmom_oszicar (knn graph).",
    },
    "max_efg_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "max_efg",
        "unit": "",
        "test_mae": 19.2483,
        "figshare_article_id": 33135068,
        "url": "https://ndownloader.figshare.com/files/67163453",
        "description": "JARVIS-DFT max_efg (knn graph).",
    },
    "mbj_bandgap_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "mbj_bandgap",
        "unit": "",
        "test_mae": 0.273,
        "figshare_article_id": 33135074,
        "url": "https://ndownloader.figshare.com/files/67163459",
        "description": "JARVIS-DFT mbj_bandgap (knn graph).",
    },
    "mepsx_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "mepsx",
        "unit": "",
        "test_mae": 23.8474,
        "figshare_article_id": 33135080,
        "url": "https://ndownloader.figshare.com/files/67163465",
        "description": "JARVIS-DFT mepsx (knn graph).",
    },
    "mepsy_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "mepsy",
        "unit": "",
        "test_mae": 24.0439,
        "figshare_article_id": 33135086,
        "url": "https://ndownloader.figshare.com/files/67163471",
        "description": "JARVIS-DFT mepsy (knn graph).",
    },
    "mepsz_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "mepsz",
        "unit": "",
        "test_mae": 23.5306,
        "figshare_article_id": 33135092,
        "url": "https://ndownloader.figshare.com/files/67163477",
        "description": "JARVIS-DFT mepsz (knn graph).",
    },
    "mxene275_formation_energy_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "formation_energy",
        "unit": "eV/atom",
        "test_mae": 0.0343,
        "figshare_article_id": 33135224,
        "url": "https://ndownloader.figshare.com/files/67163630",
        "description": "mxene275 formation energy (kNN).",
    },
    "n_Seebeck_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "n_Seebeck",
        "unit": "",
        "test_mae": 40.3457,
        "figshare_article_id": 33135098,
        "url": "https://ndownloader.figshare.com/files/67163483",
        "description": "JARVIS-DFT n_Seebeck (knn graph).",
    },
    "n_powerfact_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "n_powerfact",
        "unit": "",
        "test_mae": 451.904,
        "figshare_article_id": 33135104,
        "url": "https://ndownloader.figshare.com/files/67163489",
        "description": "JARVIS-DFT n_powerfact (knn graph).",
    },
    "omdb_bandgap_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "bandgap",
        "unit": "",
        "test_mae": 0.2411,
        "figshare_article_id": 33135332,
        "url": "https://ndownloader.figshare.com/files/67163981",
        "description": "omdb bandgap (knn).",
    },
    "optb88vdw_bandgap_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "optb88vdw_bandgap",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135110,
        "url": "https://ndownloader.figshare.com/files/67163495",
        "description": "JARVIS-DFT optb88vdw_bandgap (knn graph).",
    },
    "optb88vdw_total_energy_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "optb88vdw_total_energy",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135116,
        "url": "https://ndownloader.figshare.com/files/67163504",
        "description": "JARVIS-DFT optb88vdw_total_energy (knn graph).",
    },
    "pdbbind_binding_affinity_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "binding_affinity",
        "unit": "",
        "test_mae": 2.7265,
        "figshare_article_id": 33135338,
        "url": "https://ndownloader.figshare.com/files/67163987",
        "description": "pdbbind binding_affinity (knn).",
    },
    "polymer_genome_gga_gap_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "gga_gap",
        "unit": "",
        "test_mae": 0.2273,
        "figshare_article_id": 33135233,
        "url": "https://ndownloader.figshare.com/files/67163639",
        "description": "polymer_genome gga_gap (knn).",
    },
    "qm9_gap": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "qm9_gap",
        "unit": "eV",
        "test_mae": 0.031,
        "figshare_article_id": 33135167,
        "url": "https://ndownloader.figshare.com/files/67163570",
        "description": "QM9 HOMO-LUMO gap (kNN).",
    },
    "qmof_bandgap": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "qmof_bandgap",
        "unit": "eV",
        "test_mae": 0.208,
        "figshare_article_id": 33135170,
        "url": "https://ndownloader.figshare.com/files/67163573",
        "description": "QMOF bandgap (kNN).",
    },
    "shear_modulus_gv_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "shear_modulus_gv",
        "unit": "",
        "test_mae": 8.8254,
        "figshare_article_id": 33135122,
        "url": "https://ndownloader.figshare.com/files/67163510",
        "description": "JARVIS-DFT shear_modulus_gv (knn graph).",
    },
    "slme_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "slme",
        "unit": "",
        "test_mae": 4.4475,
        "figshare_article_id": 33135128,
        "url": "https://ndownloader.figshare.com/files/67163519",
        "description": "JARVIS-DFT slme (knn graph).",
    },
    "snumat_Band_gap_HSE_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "Band_gap_HSE",
        "unit": "",
        "test_mae": 0.3483,
        "figshare_article_id": 33135977,
        "url": "https://ndownloader.figshare.com/files/67166072",
        "description": "snumat Band_gap_HSE (knn).",
    },
    "spillage_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "spillage",
        "unit": "",
        "test_mae": 0.3456,
        "figshare_article_id": 33135134,
        "url": "https://ndownloader.figshare.com/files/67163525",
        "description": "JARVIS-DFT spillage (knn graph).",
    },
    "tc_supercon_hydride_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "Tc_supercon_hydride",
        "unit": "K",
        "test_mae": 10.07,
        "figshare_article_id": 33135218,
        "url": "https://ndownloader.figshare.com/files/67163624",
        "description": "Tc_supercon_hydride (kNN, retrained pure-torch).",
    },
    "tc_supercon_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "Tc_supercon",
        "unit": "",
        "test_mae": 1.49,
        "figshare_article_id": 33135212,
        "url": "https://ndownloader.figshare.com/files/67163618",
        "description": "Tc_supercon (kNN).",
    },
    "thermal_cond_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "ltc",
        "unit": "",
        "test_mae": 0.375,
        "figshare_article_id": 33135197,
        "url": "https://ndownloader.figshare.com/files/67163603",
        "description": "Lattice thermal cond. log10(kL) (kNN).",
    },
    "twod_matpd_bandgap_knn": {
        "category": "knn",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 1,
        "target": "bandgap",
        "unit": "",
        "test_mae": 0.366,
        "figshare_article_id": 33135245,
        "url": "https://ndownloader.figshare.com/files/67163651",
        "description": "twod_matpd bandgap (knn).",
    },
    "a2f": {
        "category": "spectra",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 100,
        "target": "a2F",
        "unit": "",
        "test_mae": 0.058,
        "figshare_article_id": 33217434,
        "url": "https://ndownloader.figshare.com/files/67452780",
        "description": "Eliashberg alpha^2F(omega) spectral function, 100-bin 0-110.8 meV (radius graph, supercon_3d).",
    },
    "dielectric_knn": {
        "category": "spectra",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 300,
        "target": "dielectric",
        "unit": "arb",
        "test_mae": 0.0005,
        "figshare_article_id": 33135266,
        "url": "https://ndownloader.figshare.com/files/67163663",
        "description": "TBmBJ dielectric function imag_xx 300-bin 0-15 eV (knn graph).",
    },
    "dielectric_radius": {
        "category": "spectra",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 300,
        "target": "dielectric",
        "unit": "arb",
        "test_mae": 0.0005,
        "figshare_article_id": 33135254,
        "url": "https://ndownloader.figshare.com/files/67163660",
        "description": "TBmBJ dielectric function imag_xx 300-bin 0-15 eV (radius graph).",
    },
    "edos": {
        "category": "spectra",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 300,
        "target": "edos",
        "unit": "states/eV",
        "test_mae": 0.0138,
        "figshare_article_id": 33135158,
        "url": "https://ndownloader.figshare.com/files/67163561",
        "description": "300-bin electronic DOS (radius graph).",
    },
    "ir_knn": {
        "category": "spectra",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 200,
        "target": "ir",
        "unit": "arb",
        "test_mae": 0.023,
        "figshare_article_id": 33135251,
        "url": "https://ndownloader.figshare.com/files/67163657",
        "description": "IR spectrum 200-bin 0-2000 cm^-1 (knn graph).",
    },
    "ir_radius": {
        "category": "spectra",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 200,
        "target": "ir",
        "unit": "arb",
        "test_mae": 0.0232,
        "figshare_article_id": 33135248,
        "url": "https://ndownloader.figshare.com/files/67163654",
        "description": "IR spectrum 200-bin 0-2000 cm^-1 (radius graph).",
    },
    "pdos": {
        "category": "spectra",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 200,
        "target": "pdos",
        "unit": "states/THz",
        "test_mae": 0.0819,
        "figshare_article_id": 33135164,
        "url": "https://ndownloader.figshare.com/files/67163567",
        "description": "200-bin phonon DOS (radius graph).",
    },
    "raman_knn": {
        "category": "spectra",
        "graph": "knn",
        "cutoff": 8.0,
        "output_features": 200,
        "target": "raman_intensity",
        "unit": "arb",
        "test_mae": 0.0326,
        "figshare_article_id": 33134963,
        "url": "https://ndownloader.figshare.com/files/67163327",
        "description": "200-bin Raman spectrum (kNN graph).",
    },
    "born_tensor": {
        "category": "tensor",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "born",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135155,
        "url": "https://ndownloader.figshare.com/files/67163558",
        "description": "born response tensor (D=1).",
    },
    "dielectric_tensor": {
        "category": "tensor",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 9,
        "target": "dielectric",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135143,
        "url": "https://ndownloader.figshare.com/files/67163546",
        "description": "dielectric response tensor (D=9).",
    },
    "elastic_tensor": {
        "category": "tensor",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 36,
        "target": "elastic",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135152,
        "url": "https://ndownloader.figshare.com/files/67163555",
        "description": "elastic response tensor (D=36).",
    },
    "piezo_tensor": {
        "category": "tensor",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 18,
        "target": "piezo",
        "unit": "",
        "test_mae": None,
        "figshare_article_id": 33135149,
        "url": "https://ndownloader.figshare.com/files/67163552",
        "description": "piezo response tensor (D=18).",
    },
    "alignn_ff_db": {
        "category": "forcefield",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "energy_per_atom",
        "unit": "",
        "test_mae": 0.0564,
        "figshare_article_id": 33135200,
        "url": "https://ndownloader.figshare.com/files/67163606",
        "description": "ALIGNN-FF-DB force field (radius).",
    },
    "fd_ff_base": {
        "category": "forcefield",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "energy_per_atom",
        "unit": "",
        "test_mae": 0.0445,
        "figshare_article_id": 33135203,
        "url": "https://ndownloader.figshare.com/files/67163609",
        "description": "FD-FF 1.1M base force field (radius).",
    },
    "fd_ff_ev": {
        "category": "forcefield",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "energy_per_atom",
        "unit": "eV/atom",
        "test_mae": None,
        "figshare_article_id": 33134966,
        "url": "https://ndownloader.figshare.com/files/67163330",
        "description": "FD-FF + EV/vacancy/surface/interface augmented force field (energy/forces/stress, radius graph).",
    },
    "matpes_ff": {
        "category": "forcefield",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "energy_per_atom",
        "unit": "eV/atom",
        "test_mae": 0.113,
        "figshare_article_id": 33134972,
        "url": "https://ndownloader.figshare.com/files/67163336",
        "description": "Force field trained on MATPES-PBE (keep_data_order, ep100).",
    },
    "matpes_pbe_ff": {
        "category": "forcefield",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "energy_per_atom",
        "unit": "eV/atom",
        "test_mae": 0.218,
        "figshare_article_id": 33148208,
        "url": "https://ndownloader.figshare.com/files/67217507",
        "description": "ALIGNN 2.0 force field: 2/2/128, smooth cutoff (multiply_cutoff, inner_cutoff 4.0), nbr52, MATPES-PBE ep100; NVE-stable (Si/MgO/Cu ~CHGNet). PBE energy scale.",
    },
    "matpes_r2scan_ff": {
        "category": "forcefield",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "energy_per_atom",
        "unit": "eV/atom",
        "test_mae": 0.0487,
        "figshare_article_id": 33190782,
        "url": "https://ndownloader.figshare.com/files/67360764",
        "description": "DEFAULT ALIGNN 2.0 force field: 2/2/128, smooth cutoff (multiply_cutoff, inner_cutoff 4.0), nbr52, MATPES-r2SCAN ep100. Test MAE 48.7 meV/atom (E) / 0.163 eV/A (F); NVE-stable; chipsff vacancy MAE 0.775 eV (r2SCAN chempots). NOTE: raw r2SCAN total-energy scale (not PBE) — absolute energies/formation differ from PBE models.",
    },
    "mlearn_si": {
        "category": "forcefield",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "energy_per_atom",
        "unit": "",
        "test_mae": 0.0872,
        "figshare_article_id": 33135206,
        "url": "https://ndownloader.figshare.com/files/67163612",
        "description": "mlearn Si force field.",
    },
    "mptrj_ff": {
        "category": "forcefield",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "energy_per_atom",
        "unit": "eV/atom",
        "test_mae": 0.0707,
        "figshare_article_id": 33134969,
        "url": "https://ndownloader.figshare.com/files/67163333",
        "description": "Universal force field trained on MPtrj (~1.5M configs, ep46).",
    },
    "charge_atomwise": {
        "category": "atomwise",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "charge",
        "unit": "e",
        "test_mae": None,
        "figshare_article_id": 33135137,
        "url": "https://ndownloader.figshare.com/files/67163528",
        "description": "Per-atom charge (atomwise head).",
    },
    "magmom_atomwise": {
        "category": "atomwise",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "magmom",
        "unit": "muB",
        "test_mae": None,
        "figshare_article_id": 33135140,
        "url": "https://ndownloader.figshare.com/files/67163543",
        "description": "Per-atom magmom (atomwise head).",
    },
    "net_charge_atomwise": {
        "category": "atomwise",
        "graph": "radius",
        "cutoff": 5.0,
        "output_features": 1,
        "target": "net_charge",
        "unit": "e",
        "test_mae": 0.0167,
        "figshare_article_id": 33135227,
        "url": "https://ndownloader.figshare.com/files/67163633",
        "description": "Per-atom net charge (atomwise head).",
    },
    # --- add new models here (one entry each) ---
    # --- generative inverse design (ALIGNN-CSP) ------------------------------
    # Conditional diffusion over lattice + fractional coordinates with an
    # ALIGNN denoiser. These emit structures rather than properties, so they
    # are loaded through alignn.inverse.generate.ALIGNNGenerator rather than
    # the property-prediction path.
    "csp_supercon_jarvis": {
        "category": "generative",
        "graph": "dense",
        "cutoff": 0.0,
        "output_features": 0,
        "target": "structure",
        "unit": "",
        "conditioning": ["composition", "Tc_supercon"],
        "match_rate": 0.524,
        "rmsd": 0.056,
        "figshare_article_id": 33315741,
        "url": "https://ndownloader.figshare.com/files/67768725",
        "description": (
            "ALIGNN-CSP trained from scratch on AtomBench JARVIS "
            "Supercon-3D; best single benchmark run."
        ),
    },
    "csp_supercon_jarvis_pt": {
        "category": "generative",
        "graph": "dense",
        "cutoff": 0.0,
        "output_features": 0,
        "target": "structure",
        "unit": "",
        "conditioning": ["composition", "Tc_supercon"],
        "match_rate": 0.515,
        "rmsd": 0.023,
        "figshare_article_id": 33315744,
        "url": "https://ndownloader.figshare.com/files/67768728",
        "description": (
            "ALIGNN-CSP on JARVIS Supercon-3D, fine-tuned from "
            "csp_pretrain_dft3d; best coordinate accuracy."
        ),
    },
    "csp_supercon_alex": {
        "category": "generative",
        "graph": "dense",
        "cutoff": 0.0,
        "output_features": 0,
        "target": "structure",
        "unit": "",
        "conditioning": ["composition", "Tc"],
        "match_rate": 0.485,
        "rmsd": 0.028,
        "figshare_article_id": 33315747,
        "url": "https://ndownloader.figshare.com/files/67768731",
        "description": (
            "ALIGNN-CSP on AtomBench Alexandria DS-A/B superconductors, "
            "fine-tuned from csp_pretrain_dft3d."
        ),
    },
    "csp_pretrain_dft3d": {
        "category": "generative",
        "graph": "dense",
        "cutoff": 0.0,
        "output_features": 0,
        "target": "structure",
        "unit": "",
        "conditioning": ["composition"],
        "figshare_article_id": 33315750,
        "url": "https://ndownloader.figshare.com/files/67768734",
        "description": (
            "ALIGNN-CSP base model over 65k JARVIS dft_3d crystals with "
            "benchmark val/test ids held out; for fine-tuning."
        ),
    },
}

_API = "https://api.figshare.com/v2"


def list_alignn2_models(category=None):
    """Return the registry, optionally filtered by category."""
    return {
        k: v
        for k, v in ALIGNN2_MODELS.items()
        if category is None or v["category"] == category
    }


def resolve_by_target(target, category=None):
    """Return registry keys whose ``target`` matches (e.g. a property name)."""
    return [
        k
        for k, v in ALIGNN2_MODELS.items()
        if v.get("target") == target
        and (category is None or v["category"] == category)
    ]


def _cache_dir():
    d = os.path.join(os.path.expanduser("~"), ".alignn2_models")
    os.makedirs(d, exist_ok=True)
    return d


def get_alignn2_model(name, download=True, cache_dir=None):
    """Return local paths to a model's artifacts, downloading+caching on first use.

    Downloads the variant's single flat Figshare zip (``config.json``,
    ``best_model.pt``, ``ids_train_val_test.json``) via its ``url`` and extracts
    it to ``~/.alignn2_models/<name>/``.
    """
    if name not in ALIGNN2_MODELS:
        raise KeyError(
            "Unknown model '{}'. Available: {}".format(
                name, sorted(ALIGNN2_MODELS)
            )
        )
    meta = ALIGNN2_MODELS[name]
    dest = os.path.join(cache_dir or _cache_dir(), name)
    triplet = ["config.json", "best_model.pt", "ids_train_val_test.json"]
    have = os.path.exists(
        os.path.join(dest, "best_model.pt")
    ) and os.path.exists(os.path.join(dest, "config.json"))
    if download and not have:
        os.makedirs(dest, exist_ok=True)
        url = meta.get("url")
        if not url:  # unmigrated fallback: fetch the article's zip file url
            r = requests.get(
                "{}/articles/{}".format(_API, meta["figshare_article_id"])
            )
            r.raise_for_status()
            files = {
                f["name"]: f["download_url"] for f in r.json().get("files", [])
            }
            url = files.get(meta.get("zip")) or next(iter(files.values()))
        r = requests.get(url, stream=True)
        r.raise_for_status()
        zp = os.path.join(dest, "_model.zip")
        with open(zp, "wb") as o:
            for c in r.iter_content(1 << 20):
                o.write(c)
        with zipfile.ZipFile(zp) as z:
            members = z.namelist()
            sub = meta.get("subdir", "")
            for base in triplet + ["multi_out_predictions.json"]:
                hit = [
                    n for n in members if n == base or n.endswith("/" + base)
                ]
                if sub:
                    hit = [
                        n for n in hit if ("%s/%s" % (sub, base)) in n
                    ] or hit
                if hit:
                    with z.open(hit[0]) as fsrc, open(
                        os.path.join(dest, base), "wb"
                    ) as fdst:
                        fdst.write(fsrc.read())
        os.remove(zp)
    return {
        f: os.path.join(dest, f)
        for f in triplet
        if os.path.exists(os.path.join(dest, f))
    }


# ---------------------------------------------------------------------------
# Backward-compatibility shim
# ---------------------------------------------------------------------------
# The legacy DGL-based helpers (``get_figshare_model``,
# ``get_multiple_predictions``, ``get_prediction`` ...) moved to
# ``alignn.deprecated.pretrained`` when this module was renamed from
# ``pretrained2``. They are re-exported here so existing imports of the form
# ``from alignn.pretrained import get_figshare_model`` keep working. Guarded
# because the legacy path requires DGL, which the pure-PyTorch ALIGNN 2.0
# models above do not.
try:  # pragma: no cover - optional DGL dependency
    from alignn.deprecated.pretrained import (  # noqa: F401
        get_all_models,
        get_figshare_model,
        get_figshare_model_pure,
        load_pure_torch_model,
        get_prediction,
        get_prediction_pure,
        get_multiple_predictions,
    )
except Exception:  # DGL not installed / legacy import unavailable
    pass
